### ISSUE TITLE
about In-the-Wild Data Augmentation 

### ISSUE THREAD

**Issue by ZhangLei999** [little-misfit/BooW-VTON#10]
Thanks for your work. Your paper is very helpful to me!
I have some questions about "In-the-Wild Data Augmentation".
Your paper states as follows:
"We first inpaint the blank areas of the person image using the prompt ”A woman {preposition} {scene}” to obtain a blended image of the person and background." 
Can you tell me which T2I did you use?

**Comment by ZhangLei999** [comment]
Without segment, I can't think of any way to achieve it

**Comment by little-misfit** [comment]
Thank you for your recognition. We use the [SDXL-Inpaint model](https://huggingface.co/spaces/diffusers/stable-diffusion-xl-inpainting) to generate the background. The generation process of the foreground and background is shown in the figure. We will provide more implementation details in subsequent versions.![image](https://github.com/user-attachments/assets/06cb9a74-e00a-45b9-b853-067899a34676)

**Comment by ZhangLei999** [comment]
Thanks for your quick reply!
