### ISSUE TITLE
attention map display

### ISSUE THREAD

**Issue by Wangxuefeng92** [little-misfit/BooW-VTON#11]
hi, sir.  could you share something about 'attention map display' like Figure4 in your paper ? thank you for your great work on BooW-VTON!

**Comment by little-misfit** [comment]
You can refer to [FastComposer: Tuning-Free Multi-Subject Image Generation with Localized Attention](https://github.com/mit-han-lab/fastcomposer) 's code about how to extract the attention map. For virtual try-on task, multiple attention maps need to be averaged into one.
