### ISSUE TITLE
Clothing Encoder?

### ISSUE THREAD

**Issue by Dorniwang** [little-misfit/BooW-VTON#2]
Which model do you use as the clothing encoder?

**Comment by little-misfit** [comment]
follow the  [IDM-VTON](https://github.com/yisol/IDM-VTON/tree/main)，we use ip-adapter and garment unet as the clothing encoder

**Comment by Dorniwang** [comment]
> follow the [IDM-VTON](https://github.com/yisol/IDM-VTON/tree/main)，we use ip-adapter and garment unet as the clothing encoder

ok, got it, thx
