### ISSUE TITLE
train  issues

### ISSUE THREAD

**Issue by fujianhai** [little-misfit/BooW-VTON#3]
Excuse me， 
IDM-VTON  Only supporting the replacement of a single item of clothing, how did this article achieve the simultaneous replacement of both the top and pants? Was it done twice?  or  Improved the training of IDM-VTON？

thanks

**Comment by little-misfit** [comment]
We trained our model on the DressCode dataset (similar to CAT-DM or OOTD), using simple text prompts like "upper," "lower," and "dresses" to indicate the try-on locations. During inference, we achieve composite try-on by performing two separate try-ons at different positions.

**Comment by fujianhai** [comment]
thank you
