### ISSUE TITLE
Try-On Localization Loss

### ISSUE THREAD

**Issue by Wangxuefeng92** [little-misfit/BooW-VTON#7]
hi， thank you for your great work on BooW-VTON! Could you share more detail about 'Try-On Localization Loss' as you mentioned in your paper? thanks again!

**Comment by little-misfit** [comment]
Sorry for the late reply, and thank you for recognizing our work. If you want to gain more information in Localization loss, you can refer to this article: "[FastComposer: Tuning-Free Multi-Subject Image Generation with Localized Attention]([https://arxiv.org/abs/2305.10431)"~~

**Comment by little-misfit** [comment]
Sorry for the late reply, and thank you for recognizing our work. If you want to gain more information in Try-On Localization Loss, you can refer to this article: " [FastComposer: Tuning-Free Multi-Subject Image Generation with Localized Attention](https://arxiv.org/abs/2305.10431) "  ^_^

**Comment by Wangxuefeng92** [comment]
got it！ thanks a lot！
